USE ${hiveconf:my.schema};

DROP TABLE IF EXISTS foo;
CREATE EXTERNAL TABLE foo (i int, s string)
  ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
  STORED AS TEXTFILE
  LOCATION '${hiveconf:MY.HDFS.DIR}/foo/';
