DROP TABLE IF EXISTS foo;
CREATE EXTERNAL TABLE foo(s1 string, s2 string)
  ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
  STORED AS TEXTFILE
  LOCATION '/tmp/foo/';


DROP TABLE IF EXISTS foo_prim;
CREATE TABLE foo_prim as select * from foo;


